KudVenkat/Models/City.cs
namespace KudVenkat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("tblCity")]
    public partial class City
    {
        public int ID { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        public bool IsSelected { get; set; }
    }
}

KudVenkat/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KudVenkat.Models
{
    public class Company
    {
        private string _name;
        public Company(string name)
        {
            this._name = name;

        }
        public Company()
        {

        }

        public string SelectedDepartment { get; set; }

        public List<tblDepartment> Departments
        {
            get
            {
                KudVenkatMVCDataModel db = new KudVenkatMVCDataModel();
                return db.tblDepartments.ToList();
            }
        }
        public string CompanyName
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    }
}

KudVenkat/Models/Employee.cs
namespace KudVenkat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Employee")]
    public partial class Employee
    {
        public int Id { get; set; }

        [StringLength(100)]
        public string FullName { get; set; }

        [StringLength(10)]
        public string Gender { get; set; }

        public int? Age { get; set; }

        public DateTime? HireDate { get; set; }

        [StringLength(100)]
        public string EmailAddress { get; set; }

        public int? Salary { get; set; }

        [StringLength(100)]
        public string PersonalWebSite { get; set; }

        [StringLength(100)]
        public string Photo { get; set; }

        [StringLength(100)]
        public string AlternateText { get; set; }
    }
}

KudVenkat/Models/EmployeeDataModel.cs
namespace KudVenkat.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class EmployeeDataModel : DbContext
    {
        public EmployeeDataModel()
            : base("name=EmployeeDataModel")
        {
        }

        public virtual DbSet<Employee> Employees { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

KudVenkat/Models/KudVenkatMVCDataModel.cs
namespace KudVenkat.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class KudVenkatMVCDataModel : DbContext
    {
        public KudVenkatMVCDataModel()
            : base("name=KudVenkatMVCDBContext")
        {
        }

        public virtual DbSet<tblDepartment> tblDepartments { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

KudVenkat/Models/MVCDataModel.cs
namespace KudVenkat.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class MVCDataModel : DbContext
    {
        public MVCDataModel()
            : base("name=MVCDBContext")
        {
        }

        public virtual DbSet<City> Cities { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

KudVenkat/Models/tblDepartment.cs
namespace KudVenkat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class tblDepartment
    {
        public int Id { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        public bool? isSelected { get; set; }
    }
}

KudVenkat/Controllers/EmployeeController.cs
using BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KudVenkat.Models;


namespace KudVenkat.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        //public ActionResult Index()
        //{
        //    EmployeeBusinessLayer employeeBusinessLayer = new EmployeeBusinessLayer();

        //    //List<Employee> employees = employeeBusinessLayer.Employees.ToList();

        //    //KudVenkatMVCDataModel datamodel = new KudVenkatMVCDataModel();
        //    //var dept = datamodel.tblDepartments;
        //    //return View(employees);
        //}

        public ActionResult Department()
        {
            KudVenkatMVCDataModel datamodel = new KudVenkatMVCDataModel();
            var dept = datamodel.tblDepartments;

            ViewBag.Departments1 = new SelectList(datamodel.tblDepartments, "Id", "Name");
            return View();
        }

    }
}

KudVenkat/Controllers/HomeController.cs
using BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KudVenkat.Models;
using System.Text;

namespace KudVenkat.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index2()
        {
            EmployeeDataModel dataModel = new EmployeeDataModel();

            return View(dataModel.Employees.ToList());
        }

        [HttpGet]
        public ActionResult CheckBox()
        {
            MVCDataModel dataModel = new MVCDataModel();

            return View(dataModel.Cities);
        }
        [HttpPost]
        public string CheckBox(IEnumerable<City> cities)
        {
            if(cities.Count(x=>x.IsSelected)==0)
            {
                return "Please select city";

            }
            else
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("selected cities are ");

                foreach (var item in cities)
                {
                    if(item.IsSelected)
                    {
                        sb.Append(item.Name + ",");

                    }
                }
                sb.Remove(sb.ToString().LastIndexOf(','), 1);
                return sb.ToString();
            }
        } 

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KudVenkat/Controllers/RadioController.cs
using KudVenkat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KudVenkat.Controllers
{
    public class RadioController : Controller
    {
        public RadioController()
        {
                
        }
        // GET: Radio
        [HttpGet]
        public ActionResult Index()
        {
            Company company = new Company("pragim");
            return View(company);
        }


        [HttpPost]
        public string Index(Company company)
        {
            if (string.IsNullOrEmpty(company.SelectedDepartment))
            {
                return "Please select Department";
            }
            else
            {
                return "You selected dept with Id " + company.SelectedDepartment;
            }
        }
    }
}

KudVenkat/Views/Employee/Department.cshtml
@{
    ViewBag.Title = "Department";
}

<h2>Department</h2>
@Html.DropDownList("Departments1", "Select Department")

KudVenkat/Views/Employee/Index.cshtml
@model IEnumerable<BusinessLayer.Employee>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

KudVenkat/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

@Html.DropDownList("Departments", new List<SelectListItem>
        {
            new SelectListItem{Text="IT",Value="1",Selected=true},
            new SelectListItem{Text="HR",Value="2"},
            new SelectListItem{Text="PayRoll",Value="3"},

        }, "Select Department")

KudVenkat/Views/Home/CheckBox.cshtml
@model IEnumerable<KudVenkat.Models.City>


@{
    ViewBag.Title = "CheckBox";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckBox</h2>

@using (Html.BeginForm())
{
   

    @Html.EditorForModel()
    <br/>

    <input type="submit" value="Submit" />
}

KudVenkat/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KudVenkat/Views/Home/EditorTemplates/City.cshtml
@model KudVenkat.Models.City

@{
    ViewBag.Title = "tblCity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>tblCity</h2>

@Html.HiddenFor(x => x.ID)
@Html.HiddenFor(x => x.Name)

@Html.CheckBoxFor(x => x.IsSelected)
@Html.DisplayFor(x => x.Name)

KudVenkat/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
  

</div>

KudVenkat/Views/Home/Index1.cshtml
@model KudVenkat.Models.Company

@{
    ViewBag.Title = "Index1";
}

<h2>Index 1</h2>

@Html.TextBoxFor(m => m.CompanyName)
<br/>
@Html.DropDownListFor(m=>m.Departments,new SelectList(Model.Departments,"Id","Name"),"Select Item")

KudVenkat/Views/Home/Index2.cshtml
@model IEnumerable<KudVenkat.Models.Employee>

@foreach (var item in Model)
{
   @Html.Partial("_Employee",item)

    {Html.RenderPartial("_Employee", item);}
}

KudVenkat/Views/Home/RaioButton.cshtml
@model KudVenkat.Models.Company

@{
    ViewBag.Title = "RaioButton";
}

<h2>RaioButton</h2>

@using (Html.BeginForm("RaioButton","Home"))
{
    foreach(var department in Model.Departments)
    {
        @Html.RadioButtonFor(m=>m.SelectedDepartment,department.Id)  @department.Name


    }
    <br/>
    <input type="submit" value="submit" />
}

KudVenkat/Views/Radio/Index.cshtml
@model KudVenkat.Models.Company

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index","Radio",FormMethod.Post))
{
    foreach (var department in Model.Departments)
    {
        @Html.RadioButtonFor(m => m.SelectedDepartment, department.Id, 
       (department.isSelected.HasValue && department.isSelected.Value)?new {@checked="checked"}:null
       )  @department.Name;

        <br />

    }
    <br />
    <input type="submit" value="submit" />
}

KudVenkat/Views/Shared/_Employee.cshtml
@model KudVenkat.Models.Employee

<h2>From Partial View </h2>
<table style="font-family:Arial; border:1px solid black; width: 300px">
    <tr>
        <td>
            <img width="100" src="@Url.Content(Model.Photo)" alt="@Model.AlternateText" />
        </td>
        <td>
            <table>
                <tr>
                    <td><b>Age:</b></td>
                    <td>@Model.Age</td>
                </tr>
                <tr>
                    <td><b>Gender:</b></td>
                    <td>@Model.Gender</td>
                </tr>
                <tr>
                    <td><b>Salary:</b></td>
                    <td>@Model.Salary</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

KudVenkat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>